"""Locked Talks N Walks monochrome logo asset.

This module stores the approved 96px profile logo as lossless compressed RGBA
pixels, independent of the historical illustration library.
"""

from __future__ import annotations

import base64
import zlib

from PIL import Image

_LOGO_SIZE = (96, 96)
_LOGO_RGBA_B85 = (
    "c-rON3H)u<*az_H-o`g1H1L`l(SQsMB#KHInkYlvgsaeS3y}te3{6UgkRcfgjb;s$CPXyjx*?J&QilKkoU`BcUG{U{b+^6GIk&l-"
    "&u4wkw9npq{hsIfJ;NH#LJQrq9#vH>oZ8H~&G7zqo^Qsv=bjtqTjchh@4on`ahchLP5OMb)K*PxozxEKX#3aCTc@^4YOCLP<Bdyq"
    "obL{i?Y$iHh1)QnH*elD>9cK9o1NM>QoAIz>d$}vbM@1o{<Qk>kAGa9ciwr`SHAL<>Wg3eV)ePteXct7)KjakfBoy#1s7aU{on^b"
    "$jANluYdKkd8wV7+B;I4MTWcYzWd@WvRLH5P1noM{`t>;J~n-"
    "}S88X2I=!!c_`@GoAN$zHs(tp^r+V>=UtGQ51uv*}*kOmkuDk9!HD}J8sRIr;VCs-"
    "V4w*Xm;Dht?{`>Dg{f0NZVQRPCcI$7y{r1(i+iqLE@|CZw(s9+vC!bthcinZ>^z`&U()oXu+A*m;BVBq%<G${*Hc|I)sAtz)bIpU"
    "(`+ZV7FSURE_P4*SKKaQ{R<C;1tE%Td_qn}Uvt~^ne)!?NuYK)ny{oRes=Dc>o2p)~S55M89D7N&(oZ(hOEQ>#*~?xwz4g{xS8sg"
    "d8>?@B``d9YvN+=JfB*XiO`maJkweWhL);TDte4&&lG<+p@cGYwzDn58@7_TN9n?GPtg{Ax`qQ80!*gnCs=DQtTdKeO<u6$do|_H"
    "dl;1nPl$Y0Y=gu9RaKZ`wop;`Odh^XU?;m*Jf!QwV$4SZVwoCUgv(%Y;Irc;QPMAD3y+1`q|L})DRBwCR+p2`Y^xk{#-"
    "B0>Bz&Y_q`Z&b(=9_QsY%q@Jc>TA({VlgRCgkGvzy9^F;Wd8!>t9#L9CJ)R+1fOI``-"
    "7y7hnD4AOHBrtC9~{{N8E{Wt>;@%qLPC;DqG=2AgiW>GZM39y_?<h8u=>gnq*-"
    "Fw}fr;#s~f+o<1^E#w;VW?QG7b{c=t+h&_>df)&4_v4l>Pj<LLn=aj3bUyWQkMur+oNRrt$tIih-"
    "v9phXKYG6Z`0c*rfqs%9uxXMN>0slg)HK6=9y<!NjLhlXV0FdD>ZMOoQ_?tsaN-8o=@1UUdN7A@}Jd)8*bQp>s#NNx!EK7-i2Qq-"
    "erS*;6KhTM&V!DL>;eI{eHjtzz051t-t>I{o{^1ZcvNn#-"
    "uARx~KYuQZEvY&qF6}dXGK!=q0~8_|cDklsj?jt+&p{>4AH+QTje<^P7^x;&q#xN;$fIy!QCjuYOg%<Rvc=^Y-"
    "Gi<Ufu`PfOpE_$YM2{UpD2L?+J5FRz~Y%xCrvJ@n9F>_PWSZXVUTunm0L^uJ9G<!{EFr{pu-6aL{tANo+W?z-"
    "y^QqDK+eaazzocg)aJwXO>{q(#-@?)2}Kk@bk8*DHTV|%pmbW`WM@EnD4^SiF!Pl|tA3%-<7KmF-XuZ}<d_+G6~x1_d1-"
    "S<WBPV5tgD<++|%6%n$pHA^y^_$=PCf~RFZ`1cC-"
    "%Nsa6RS4eZGP4!qqg&mvLUv>C&)>j|NQ66r^_VpZjnJ?pYCt@qz6~Hk(B#S%lpN1Y!~+UzNza?-tUTQy53Lfmq+P-"
    "mu$MONd{sya(Ma6U(T=fnL&EbKW~3m%AnBu6_Vax3Hv#7=1lLh%PvD7>;6l8oA`HO8Mp)|jpLC?IjQ;FCWmph75D4$>Q}#-"
    "3<m!Wm-^LR#YN$3aZb|n%sFp*)0?K%Y$C2~a(ol#uJ}VEJ9hrZKmKvPxNt#mA0?}C$4zprkbyp@z7J(kaM8>=vwp_cCcV#`^X_-Q"
    "TU{&PPg@S!<o<~B+W3Zj&z(EBQfpHiAP4<w#*<w(Gb#5>f_>NT%j<iHPmetE$UzGi&AhX6EAdxdH=BOp3tuQ6Yvq}7ac1;0eB3v_"
    "@r_(B-hA`TtDSb*sXF-JgR5_T^PAZg$fgVTHe5$>{3QI}mDiPdqG$Cab@7xpXFC`Sa=P}kJ32NEc_tYjQO9G`&v?c&vX1h#Weu!Z"
    "e`(9F%KpOF7|Np`{pf1pg%_?|F4{vL@{pX1x=xuNP3l9(<;h(>cT|lj@OOO519GgFa-HhuKmWP7hyd{Nip_fa?e(`w&$obm;^f}5"
    "pZ)Agor=7Jx7*_SQWi}ciTgK}wd$&?X1w9Q$RdkWGiJ=F7F~4F{MnP9^rU<(*CB_dPiWSCCTXMm^tgDm^kb19eCIpgsh;<|=ZXEM"
    ">$vo@FiU#6=pDrQD<vN<37?)ld-mYNAO3Jv%i=$9?}{^<a)G@u7kuMVGiT16Pxr|}V;B18LEhrqsGGIv=_I~)QcfCIR|@X*c>CMm"
    "UhTKvez~Mt%V6Kz>kC5nQ=iXq!q0r>Grfp2qn<FTj??uzYVlwC(wC}7JmL{Uy>H_0d9Ah9sy_0Ok5r%d#3!mxed<%yWtUx+>lu7="
    ">6aH&|HtJAlboZhF}WxH&{zh4EF4U2&D-h=3hZA8?;CEoVH)qyS-M-sGEMB;;{6hT{`B|1|9!5zFSp!sLtQWNkJgk6UfOcYEvt(!"
    "zIYh(P9lf4_^2s|+gk5qi|kUJQU0HFD{|xuQd?rw+>TMalg|6Vns@rIdChAE#%J4jXB5}B#cuoszpJkDoaa2J73Zcc_`W=5@x>Px"
    "|Bj50Msd(2b&qjeRQ5Z@5yWjr9FfD6@C7?AC=Z3-"
    "PBP7apL_1Pz3sN!ZfNsu`Bj@AXxc&f8#a_;hU$zn&Zt&jef6x@T{h6<r|=c`yWjot90@XL%kP?X%}L^;asIb$?5DJGa@b;vE!403"
    "wG6IL`u4C%<DsIaxekAqFz=Z+U~UbLYsQq#_<vju*8Coyi}TlAcipjeP&P4==Vv|ZS=o-"
    "*RNFY%Bz!b3Pafxs<C@`%@x+`tb4nXHdQuxGc>i=iJmr*Adg>ifOKxJT?_D*uE_uY~d^j1avD4{Eu`lDJ#THvE=MNDJj~Xu?mD6_"
    "RaZP{QRmUo?EhnP0S6_W~)F=4j|833%X~VugW}V)@AANHJ_!WBY8f<{B;Ucm7o_p?@W0|)6x5+(Cx$s$+UV3Tu(1$*Bfpov=n|Ir"
    "7x9kJL1}3SKc8$%KGH8?CsImR<#U6BG@4fdfZQ#gpHW1$>Jk8guzWUX#4r^=S<M9yQu4~R&cccE(#rthzudwpDap48QysL@7`IJ)"
    "L<Mh1k^GR!@<NUPiZ?nxd*$>n_KDUmATF3Bfz1LPq$NmwfJMX;nAo<?m_@T$)haX-"
    "Yb<|N=|BpTP*qoD=+}kyep(ztKdhNB>Rxf(di$=zu<2dMn4}4&L7L%&qm9g=tIT2kxbU|XHE^Z4OIOdpRs`tF-"
    "Jyo3#WJtSgK<yg-NyoF}xaOK`a&0qsC*}vpnNlq3`|64-"
    "uE^iRGW2<zPQ*RKNv+d(M(IzZEwRKB!x}^>n=%fS8$aO*Psp$Ft$DXmkLsE`)K#~eWZp&7-"
    ";UxTd}s`xe%1K^U+|;Q^)~&l>pbRT4&L#Ocl3f=f(xVGG<){!Jg<cAvn}K8zx&<qhGQ>nc}=rlxQzV7%T0{QLVREP1F~3VnPu{Kj"
    "^#7d9-sEKr)A%5p02ueaL|Ixp}0MHaMwA4FZS4Dk32V<A5P8u-!+<ZSmJfM_mvZ`+?wRoPx1bMJ%?|Net0<F>8GEbF?`p%-"
    "j(HX<Bd0FnUAaEmN~F_h|aU}$}7)j17aFE!Ts-"
    "l|BUqtE3A;~a7!+^Wd4pE9`v9GW!+kS`Q`Jm>eu>Q=3=G(FKBINT%B&5d~p!n)IWZ*@WcBxIVfHyJoj|Kg%@5ptrj1;A8|hYhB<v"
    "#lYGlt-jaQc7~c17v2xq^OEg%SXO1UfTE>;@tg}w8{rGI9l~&3;v*L;?W*I%|QID$Bztw%!PLDtS_-u=%?l*mK6RQQC-!-"
    "aU(N#ZnefPD)4m&uuSI_Udw3&<5apz)5*T0K<4n6eHo|;$S4<~)R{`%`P&SJ)ofBfUQHcyAiq;0HXTpbiw%U!?x<u7MD#rd#bcG+"
    "dKUekA&Z?@TH<^|?j1-Y!T#u{RSYOAfb%5jhDH{;x{afeCAFc-"
    "8A)ON1mATjz`XPuQxxCwvt(Y2fN*3$Db=CwE|`NY9be)5wX<2VmH+IQc5v!3SS_GdqvWB+ozy(_jTb)js2=l;~uQk<LTp}+afZ_a"
    "qrb-EA#m%j9+c|7ciPkdtbvHZ1|SboW_zx&<q&S$4x_3lZ1!MJ+!BsJ@19Heer&qWIkdUdh(W@hboxAA@QuRU>3jHv|v=2PJsepX"
    "Bx_;uA+y6io0;aAMPx1K2GC(@HAKl#bIj=T2SYiA$JE?)79S7g4S^Skc4YhK&p{d?d0UN!N2e_dk{lVUn*PDWdfHf~N*;DImjvpz"
    "%|n)LeAf_G-tzIV5JzU;JEqO5Z|7hB+K&p!L?%-"
    "KFK=M=WZXrnkGeskrOSLW;RQ+zD_#w+w4AF1!iBVn!&WaBvYf)`Vqmg62=)|G#c(*3r&-"
    "6Z2Wlh*FyT>6!`I`V)EYwTwf^`5W#;;_RG>m7I8ar4=9j4|r3wQd((bWzq{vQ=~91KM((l55H_%BVfWgZ>*^FrPrJ$ylDo2Z(dj6"
    "LHV$U;p|XD;;^{kySkxGjrlEe({U>Y9LKp8yDNR)yl`c9>qbW?u8F{?Q35<9J8p$$R1VLz@mx!zgN$t>V4~5-"
    "x`i>M9kw{Y(U(9$t8J7Vy;`_1ik_mF}InV!Y4NIkFl?L^X6q);zqe^J+CbDi<;A{S+jC%V~t~suWqu*CRON$bLfvb`{lJtnRof(w"
    "*0IuSD9o?r;BH!1^)8j6HYjxs`D_9CpFgBR&~vx`q|HZHq>viCXBq+PuxS__;cJq7ad#9q0%p75b6shHj#JX{S!|-"
    "G5eAI_uoIq@#Zel@7;IbJ^NdJcY_T!$oPB6`@D|0$=VrQDCTVQ?QPhXb&{?*d86u@3sQq9eLy{STOD%9A?5h+fq}pI)UgH#4micV"
    "hL7BF#~pLMfuDoFycJe3jQ*E33S%OCc$0%;{=fTB$56|Yw;9v?=tn=AZ2-"
    "^U8?qJuumi_NeKYRsm%sewP)|y}Y4Tk2vjz1LUAE9ww{Ei$xSey(In`c!?N#ExU*MnmuufjAJa67Wf6F>zJ;!ip_u>_}8@~;ig^o"
    "l&`AI&%tc!+htegJA7rs!PfByM7XT=}#X)@r8k3Rb79A9p<(MHu%p7NAD?k*Q(zv`}GPZ}9?#hhI}zipjZX&a-"
    ")2X0FqpwSV1;{yu(-y8TR?ze6qW>Yx0oLk_xuu=E4Mv(8V>lwp2ATS9(p{B+ks9n&{sE6S%-"
    ";tf~)XL;uxQtK1an8?|i)Y9We_1>I!4G~g=V;<Dm`AMBHLla-p|0;o&DU$oA-"
    "l#l$KlU*<*s<vm`aWRRe^uPE#sf~bV>{!*v5QVd?eoEKVU}>!|vf~3>Qzao0CpDDc2?NHw?+dJ$N=IK{ouR+Mry5UR-_k)!EPR$M"
    "Wh^PB|s#WMqYxycQEUH`|H4unprTzGY2fl#gheH#~_Qbj^=%=AQIQT%E4luXBL^z(48O)azdNx*`7L#(&G*@DhJXrvulBiP#J-"
    "Q4_MR7iQ!g<Hht<yaRvwi^KR+Hb4%Z#Z*2gA6!Wm&WWe^dcM~8>LBD+`rWSaf5$jhKSB;ozuWeCS1fva>K4A^-"
    ";yqO;(yv{r%j1J%G}HSdCmTD0o^U*O}@n*3phe8z~>&pJCQ%b53V?c|Hf(TNP|E9=iAwW^TV2)HTePgxHdn8r%D@W)9Khl;=&6r%"
    "=IeQ3!V&&=?6Vv%Vaca9rtZ%O@B>?lO1&8pK{PCaZSlTajzbHE**wZ@QOZ&&(#8OP^{@K?HU&1FZ|C&;H%#n+<ndugbc_>gS%tHr"
    "{FnbZgOSkjF_s_UGIHIMr7xA;w-"
    "l7d@+upxo>=jFUwl{ByyM}Zf!n`BS+z%cy>PiDeoiZR?uPm9I*|&`B8I1^_{MlHmy%MhTQZK7O?dhE(`t-"
    "?jeVG4|mU+<NOx4ncsoOoV$!&f@kPFIkPLrx?j4%KG`uY7DtG!@EQEu^5^EffpP2Wn{~(Xc;AW1+xREx@LPR$-"
    "g)N@{cq{t=s11XKk+*KbH6bU0*<hWu^HF~|9I%PxrXAJz(qd6C%~Fa!w!7sGv^Fn<2%iH`C|KKcwcf*V6QG4oMUXw*i6)`#lGao7"
    "Wo#}g^50eJ&hV8=$hj-?)#W;DYq&7?-hZ6dY$JxB)yyxqelFR%jqir3ls01JN9qE2XxbSu!IX6V-H~ijuW@=p|B+<&-"
    "Br6U@ot99ln7L@Cm*nqiFDEKdxtN!q}+mgpcw}Hs&L_mRRFq4|`a~Uo(d0y&8rw1NNxKCs%CRd)J-"
    "@UEDKn{5bN(dJbX4pK}BMgzMJzo*+GOV;NhJo%s&tl}62<FLh0}tbPD9ysUl(w~&+bh+pAF-"
    "{2c^a6h<)j^hX4!`U(H#ChnuXP<c{Gflq0-"
    "{5o)*I<)mYkvu~>xV!5;rW^Fues)$c|2j2RaU7U{NM*yOD(lj&aI8*kabsV)RaNnxL4blSCf0_AdJjYD#id#D(XKER~I5DV`Xe5?"
    "kVgVkCGqE;6dkIhmGSFx))p(*Chw|lAmMr6&Lvo{>~vz73Uk%@fn<broQ7jKJ(u1*$Ek{d$K>=!G6T6`e)6Ix*cpE_qfMp{I$nC<"
    "}uk0)KtwI<>$)#ZObFN>JF3EgUT9$T4kgD@WulF$4324?SQSveT58SPXste4&{Mo)pH_-iyB-Rcj5{h1jpci*pdSo;AJ-"
    "A{4f?5i5DH?HJ!)XVk6IdrdXP;#26$lS$gTEv(6ho^GxqyPxn__ZMCfXWPp2O|CLcSqH*imy2fuxIYr&27y}FZ-"
    "&u@7E}QV4Ti2ia^r|_hE&PFdCWB9Z`qNcivxu?H`Qpx)t0-TU8^9R9;BYz&d-"
    "8y(+!k+m?HD!|xq;*O2=PCE$;YTg8+$hvz$WQ7et+a6ADPz^1on@A{NwX6#*>Yu`P{unZM|(?<fvSFTs^66%scR>qjazy15<<Es+"
    "@0|^fxc^Nj%=e7cu@)>P7f+4Iha~VMK@VMARn32IS7<jw^!yBkm0Dr_XrYHTiY^HTEzRuahqsI*)My>y_jv#%aVf#^#^;)Td^w&5"
    "OY6c%IH1OU6Nb6kmn=qQ=2@i+Q4tfmw5`sB6ri<g8KkqQKv}A^KH39$kz9FC23|?eh^iKslxzc}-"
    "bMi#meXUtG?$;~E&_9{Mf5kh6+Q>Aug%3a5|<oIM*yWG8rytoQ?d;jqIF%lNxaj0>25r$#Dv6wkol92Ij|=sEnoHeM}eh`5R@=?X"
    "c&?|ttZ&gW?MbJX}i6XRyxv}p^GAF1mnei+u?QhPwT7i8j!9qWBI^Ss06{taHcUowyjsH^B3zA$eAU&|+Pa^%HyTg}cGjqf7n6yJ"
    "~mT-bom={#-`3z?G}@i{vqH-45pHr#N-"
    "oX3*|d$1=4e@pN2j~LV3Ie84s>6~2H`MuV{w%D9|Dc3cO+Y@IL)@?OBdMF>M=TpV_?>WWTW9;9vTDlMO;|A6m`Aw`pkMq!FSjS$F"
    "I9V(x_Ve(aJ~`I+?44b_^PTU^{g2uy`+&a&S8`HYvNxn!9=?kCrF@a^$=hf2-8>-"
    "8oS>MKh2zCO=Es>UBZgp0t{Y9P0Dss!muI@+e%$Y<@x*a8&Ndm8^Kk1i>xexMDEFVO+u}*De*wGX1N!3YGA{{Ru*Q<^#eM-"
    "|KYd{va)78ek{#Yqw>G9i7vbqQ`ioEE_u@wJ4_VPwe#$f17@rX{MP9%L#P<9E-)mk(<hXn<9l(p~3-"
    "E?JJHmf{%MPQqghR;#7rCc0pB}Yu$f&WLX3fEa?$=}Hu}{HfjkQLxzCAnMq;J!5smP<s`ijqt2a0EKkyuWD$xB~DkK_!#!?idZo^"
    "&#DFa1C0po6k+Fn^S;%AfEN{P|=tKRd)lxZ7{>mwJuyAY)>53w~m2F^2Q_P3XS!s5dyL`@wHf1B`gfx#<Xfpnv6Bm$o@{qt;WE`I"
    "lIP&KP$|x*c@~n<Fh1df$-4hV?w%JO|7DmHCtwbvQWbA35j`Js0cKA;-"
    "kH3|@f~?4u6sytqb8;x}vxuJn?BjNhq~k*!#lufb<z>3r~nw>XIW;16?p?|wAL$JmV+fvvFvGVop0TiJov<_vgU#vUc^F~6f6?=J"
    "T#E%6WCckk-+1^0X;xTkIXOTx{by!5hfETx=(9-"
    "L0!=m}niyWCDZ8Sz!@JIgPK^>7P)qw{<%Kf;FKi*xXnoLk??mA>=4^gr@l@u#r~IgGlcwWoBJFBS{Io&B&g*t2(7d+&VmbiRokeU"
    "I1JX6S{!xIP)U*RX?-LG&qd%!pfKEqHT{SmeENZ$;d{S=*ZIf`g8(YbsM>i<r|L_ra#*O5(-"
    "5z&Q0;j3dU<=cwo46>*|m72Yv^LZ9(5yYw1{Yykd|6Y%MNAGregvK4+6hWt4jq5t9>n7R-"
    "B4Bnyhc!*A@eK=O0>^@>#$9338%z^Y7dAo+^z?&^QxA@q7`98SM9Aq3&?|m}g`UbWv9;|C_4!GVLq%rGG*R9Vrz_awX%*CR{@4oe"
    "g{Kbo8z`tp1f{wB~{dSM=pl`6jHSmTNS?~uj4(Xn8w%<4oHgpu;YO~JE9{3yY{T}{-"
    "JzaJ!c1rijfE}_OHsBcd9pf`(>w9vFu{O5g`tFyWutWLw`s=Tsa}K$bd19~?huK5HeZho&2KSJ6y@q9?b*LeOB(5*QIQgcY`bx|<"
    "2>fF_0Jq7L+&`NY`|x4<#|Fe)YyfBDb9Qe$S3l{s_u^4{ug_82qnG3kcR0ZW-"
    "_SYo)i1mcALk3~osTWS-#x%yyn~12l(>p+#PM-%^5z@Z5P6eD*rs#hB{|)wb!g_L%Ej3Tbr-wI|B^2p)VlxIy3X0T1~uf8o?lqYY"
    "g#-mekj)hxPN@CkFh@>8F}rxFr=4cug~fP;uX5-bA1k*7k`iexsd_cuxEPdc;B-"
    "v=TST0E5viYhds;!d+%ZGzUaUAuE$ri7uVoFf}6DP*N!I}wiP_&Gj>2P%(u24>H!aUK$eBNl6*t%p`NYpuB$c`>lEosq5Efy+lwP"
    ")BR)zxel58rJ+(*pko(2?xIgw@;ve`?@4eP=i#P|Dut_{YH{c2{n7}rCGI^1Ke*0d(@f7UEjQ9=5@FR4J92}zsm%x(Uz|(8zfipZ"
    "|PF{G~d-"
    "@<Z@muy0<CWo;o!|96^K0a0&NYbCm>j2Xv1VWX;UOQPb2x$=>V5QkHJ@)h$zCXh4a^D~P`@J2nD>eU=walqu2VL;Kn|WA0}~jiZQ"
    "~60uh04qCl~~lFeew^<1fCB?`4B>E&AxV;GKwf#5fW6hm2v4_takaZv2l^$P<T)y~2K6-"
    "|y)I8Hs~pd<PH85rc1V8GB+6xJRu|j8Cpn>#WzR#C-"
    "p6FUUSLMQ$t@9wfc#%k^WPH+jMn*TI*6q9<A@2X+zj+4Rx;HT5%?;t9CJkzLSpe#C3Br`Q+A(Nn%e3@gTmQyJ^Po}N38*S?GYhv5"
    "tSM&ql*L2N{$r+g{@M4w`ApY!`Y|3enuyHB>`zGF>ntcCU7cuuU>!lB|u`DejB&s;$KBNke({(axQ$6klQMdBm+g*!q9bUtiA3%Q"
    "7G=#!Ypd~^C}4UxD+Q#XK<Tuh7yN7%!PKQ!JV1`2(Rni}lsde~IVE2aDNLyRIeai3&D4z5j~)%(OTe2eRow{wV@*`PkLJI~?;yej"
    "r??vntASdXA4NbUvp$J~~EunHdfLi~jXzZYwQ`C<13Gq||F@B@K=?B%J6jmQZ;?3ewJDL#P{9}7=$D1LzfdvFc*j01xs%2)^X;cw"
    "|F?ueQoeWA1D=)SG%(a6{D$dGJtB0ePxa>h&IJ28S|_`H~_Ck7#N>!gh5kQ=@7Ilipd4h@q3MEW<^G0y_;#aGnj9#ro~&=X6EgYh"
    "B#7x%!!IyimzIUQ;G19IVy@sL;!9`Zss`3+tZ>qmV7J}|~@`YP7MPh=Oql8$S^-8jRsaOd-JJUtg5!-"
    "&3<LBx|$2lXEQe&@Q5rO)KUR>e+^b?@QpV&1pkizB>tjM{8HS1raEXWgDX;0hkvF4oQHtLsD_9_u0LD17vdu7~c24Cryhn2ym$wj"
    "KEveJ4ly8sqzp#}VQl{sKS4nLmbg%xi-cS&CQK6yHft*d~7?4kRbnW@EwiY{l`K^Rp)$<sPg#GnYoL9b?}56?LE(2V@iO$z1t*9b"
    "xd!nRmoqtc47Y3LfIyac1P(c#rMrcZ?y@m+-&AOJo37_=>e-k5zruPdKm#u{Rm15z#^CWM6QQC&7)ZeFlGaK!4%y-"
    "i*bQ8(bXc_w<zQz}RtoddM_n;&|5}U-2IP5(}`M7{9}-"
    "A%mzzI<EG=F}>&7dJoWr?|}bL%sD~g2YaVnS=XWZbPH~DAaWJDCdPpePR5yRmK~4*ZX$zNcj_GK+;|uN!zgSTFX%U)2;1<f@P;Q@"
    "@f)%4qd3O7j78#QoE7tEqMk>den)OmkBay=Vk(Uct^W|uyGJ=Fj*Pl`%t`jZ_k0u1PkK02>;I;A<UYj37#UykuR5RZi!IzAeTESq"
    "CePxh;YlWRCa~uN*sH$q*<x_}$2bp}!4;3fSxp%i%ZD^_)lZzR<|g0AgVs%YmLrPu`4yNLpK%{@I=+R^A-l-WBL4`?U7L(t*Kf(x"
    "Z(<)M92oH}zQuR+gWT(yZ~VE{K6l1m=)ptwTCef%B_BMHkKz&hqJQq0zL0})GVu*vCj<V}{i|Q&FZLogcAWR(QSwxCGR{jr@)|ts"
    "80Qr`u@|o$PZnC(BOl_m<J1h|e>lQ#z#IqR6I>>q<cs3>bVxt&eaz2r&uoWI!Jh2MUz}fKAO7}p^*%l`t2^O;k_un2L*xZyz)oYV"
    "Am&Ta74ZZefm5ty!5R7zV=;VM%tMcQSnPog3;63Ry`+=ywH^&t=An><?_9^T<H=raKz)Wz<3Yc5AN&bB5@-2Ne8Weuk*J^G%ksa-"
    "#G<kHZZ2Y`9GX7Vb%m*N&*3|Q^T)_w(U3uX{k~XN?p^Qsmt)g9{~Oi<`8d22|7%muJ&SRUsISI<2;whsjM|I6e%Oj!4X?o2XLL|*"
    "E*>`rh~4;{Pb3dDQ?Ws;BM!YL_sACm=jK>ejCscxcwV%a<j5XtSp@c<uW`Ri{wuGL!S=yLp6M1_h&9Lh7V~h$NHNEL)Sd)^gPcbb"
    "SE#Y8y|1_4dKqh+$G_q)_{aK4Ji%^UA3iY`EXJ<NbuKY)wuyIh{*UkJkl(ou|5L1C&zy62{5M-^2Q>%gabvmu#v5-"
    "u+?S+n|BbHoTFtTSz)s(B2u>4g#kw;xCEFN#3Y^M)#+v^%(6ujh+ujrr<M092B=Z#wU;Ej+^MCQ0GKhL<>?<s0iG9msZfMs$*Jf+"
    "(H5K`G>;u)D@7){&?^=i0HczwpeeCt<AukkT)qAk_V;)28Ywt47nV?RzktG~qn~CQK`~fZ|4-"
    "dLpa{Z|NiktgowXNwHx0ZUGjGMBEHE;D=^jt6J*XulMy3nz`?+Rag8)P8oJF)yLWU+kIJ7dj!xo6WP>({$@W7OKLw&S|46>}}aXN"
    "is6bG^=OP;kBfd)o4z_+Ol5ZQE4D_zy^WBR&%I%aQm=xj_8)Yq_uNC_QcNC)BpD=%_XAZTt@Rh||2s?|5D<r2dbc>F_P-ajLyh@6"
    "P|cn{?bJ_V2cJdg&KZyf;v%!%6A}^5%GydsmM8Pk}BxN9})A?#C1VUljkttZpU8V54HLI-"
    "U!j=Y)5;H~kNAA%n$I+o_)SGL(ZguyU)2Bjsaa@pwd>+T72p>wkT^_FO9elRWq({1AUCmxH^ph=lu~m?ISrbD<tl?v1_Bz2wo@Us"
    "2uY@D#t?T>1tvt2%&Mg1kZ9MxLZ*RQ`8+$fTTWU#@*C|I;?sLpFae-"
    "%@vwr>hf*<>kKV_<qB;<|T$vL%TEoQ|+#_h5Gf%>e$vEH~QO4`rl7>Fu(!oamJzKn(_%X95RVLKL39SXZ0U4A`hIRmSN11FNL-"
    "9sqv_%UU%Jff%#BK>6|y!9KUgS@AtI-TD~3sqg2Xav80~{5WZjR$1>z6|M_6<SBgKfzhEEm!&ho@>JUDQ{j%WdImQn)$AtWnEc!{"
    "$do||G>s?p#%p)6qY{o+Ou}3Y3=DbsW`hbM_Mboi)$NY~$joVb>mudUCUw--J{Yx&nq<{YT=jV3u#TWN4yX>-"
    "lirM=qe#C3j9ax91^G6@WF{v%t*oXE$hkHkyG^6G7wTzi2d`?U4{3MQcqFI1Py%y(cYkpEQQDMu}{-"
    "@=CCl*=gzwps!6UBEc)%I~98%gpwEMa+7TeF`+?N?4p?+r*DWQ}KPtG3NKuDShQ71P`WHnB*7%OZF1`Des_zxO1}{|_(mW4Z"
)


def load_logo() -> Image.Image:
    packed = base64.b85decode(_LOGO_RGBA_B85)
    raw = zlib.decompress(packed)
    expected = _LOGO_SIZE[0] * _LOGO_SIZE[1] * 4
    if len(raw) != expected:
        raise ValueError(f"Invalid embedded logo length: {len(raw)} != {expected}")
    return Image.frombytes("RGBA", _LOGO_SIZE, raw)
