"""Men-only simple-English quote layer for the live publishing pool.

The source libraries remain attribution-rich reference data. These production
overrides keep the current Men quote ideas and attribution while making every
live quote easy to understand in one read.
"""

from __future__ import annotations

import re


MEN_QUOTE_OVERRIDES: dict[str, str] = {
    "SG001": "Small choices shape your habits, and your habits slowly shape who you become.",
    "SG002": "Make good choices easier to start so you do not need willpower every time.",
    "SG003": "Set up your space so good habits are easier and bad habits are harder.",
    "SG004": "Lasting change gets easier when good habits become part of who you are.",
    "SG005": "Missing one day is okay. What matters is getting back on track quickly.",
    "SG006": "Improve how you work instead of staring only at the result.",
    "SG007": "Make good habits easier and bad habits harder.",
    "SG008": "Tiny improvements look small until time adds them up.",
    "SG009": "Your power often begins with choosing how you respond.",
    "SG010": "Decide what matters most before urgent things take over your day.",
    "SG011": "A clear goal makes daily choices easier.",
    "SG012": "Strong relationships grow when both people are allowed to win.",
    "SG013": "Listen to understand someone, not just to plan your reply.",
    "SG014": "Different strengths help a team when no one needs everyone to be the same.",
    "SG015": "Rest before you are too tired to care about what matters.",
    "SG016": "Good character can take you farther than clever tricks.",
    "SG017": "You do not need to impress people. Listen well and make them feel seen.",
    "SG018": "Winning an argument is not worth making someone feel small.",
    "SG019": "Remember small details. It shows people they matter to you.",
    "SG020": "People learn more when you correct them with respect.",
    "SG021": "A thank-you means more when you say exactly what you are thankful for.",
    "SG022": "People listen better when they feel heard first.",
    "SG023": "Correct them without making them feel small.",
    "SG024": "Good talks are less about showing off and more about making room for others.",
    "SG025": "A wish gets stronger when you decide exactly what you want.",
    "SG026": "Keep showing up even after the excitement wears off.",
    "SG027": "Choose people who help you grow without making you feel small.",
    "SG028": "Fear gets expensive when it keeps making your choices for you.",
    "SG029": "A goal needs a plan, and plans can change when you learn more.",
    "SG030": "Chances are easier to notice when you are already preparing.",
    "SG031": "Belief helps, but action is what moves you forward.",
    "SG032": "Success grows when plans and steady work come together.",
    "SG033": "A lot of worry comes from a future that has not happened yet.",
    "SG034": "Come back to this moment before your mind turns one problem into ten.",
    "SG035": "You can notice a thought without letting it decide who you are.",
    "SG036": "Peace grows when you accept what is happening right now.",
    "SG037": "Life is happening now, even when your mind keeps wandering away.",
    "SG038": "A short pause between feeling and reacting can change what happens next.",
    "SG039": "Be present. See what is happening before you act.",
    "SG040": "Do not let yesterday and tomorrow steal all of today.",
    "SG041": "Use words that do less harm.",
    "SG042": "People's reactions often say more about them than about your worth.",
    "SG043": "Ask before you guess. Many problems start with guessing.",
    "SG044": "Your best changes from day to day. Give what you truly have today.",
    "SG045": "You feel freer when other people's opinions stop defining you.",
    "SG046": "Speak clearly so people do not have to guess what you mean.",
    "SG047": "Own what you did without taking blame for what others did.",
    "SG048": "Simple values matter most when life gets hard.",
    "SG049": "Even when choices are limited, you can still choose your attitude.",
    "SG050": "Having a reason to keep going can help you carry hard times.",
    "SG051": "A hard life can still hold love, purpose, and good choices.",
    "SG052": "Ask what you can learn from this hard season, not only when it will end.",
    "SG053": "Hope grows when you care about more than today's pain.",
    "SG054": "Pain is hard, but you can still face it with self-respect.",
    "SG055": "A reason to keep going can help when life cannot change right away.",
    "SG056": "You may not choose what happens, but you can choose how you face it.",
    "SG057": "What you can do today is only the start. Practice can help you grow.",
    "SG058": "Do not try to look talented. Be willing to learn and struggle.",
    "SG059": "Feedback is information, not your identity. Use what helps and leave the rest.",
    "SG060": "Struggling does not always mean failing. It can mean you are learning.",
    "SG061": "One bad result does not define who you are.",
    "SG062": "Work smarter by noticing what is and is not working.",
    "SG063": "Mistakes should teach you, not make you ashamed.",
    "SG064": "Where you are today does not decide where you can go.",
    "SG065": "You cannot fix everything. Put your energy where your actions can help.",
    "SG066": "A good life still has problems. Choose problems worth solving.",
    "SG067": "Choose values that matter even when no one is watching.",
    "SG068": "You cannot focus on it all. Choose what matters most.",
    "SG069": "You may not have caused it, but you can choose what you do next.",
    "SG070": "Do not let comfort make every important choice for you.",
    "SG071": "Say no to small fights so you have energy for what matters.",
    "SG072": "Good questions can help more than telling yourself to just think positive.",
    "SG073": "Train your mind to notice chances, not only problems.",
    "SG074": "A dream matters more when it changes what you do today.",
    "SG075": "You do not need a perfect life to notice what is good today.",
    "SG076": "What you expect can change what you notice.",
    "SG077": "Hope becomes stronger when it changes what you do.",
    "SG078": "Focus can turn many wishes into one clear direction.",
    "SG079": "Act like your future matters enough to prepare for it today.",
    "SG080": "Thinking good thoughts should help you act, not replace action.",
    "SG081": "Change hurts more when you keep wishing things were still the same.",
    "SG082": "Notice small changes early so you do not have to react in panic.",
    "SG083": "A solution that worked before may not work forever.",
    "SG084": "Move on before anger keeps you stuck in the old place.",
    "SG085": "Fear gets smaller when you explore instead of only imagining.",
    "SG086": "Being able to adapt can matter more than proving you were right.",
    "SG087": "What feels familiar is not always safe.",
    "SG088": "When life changes, learning how to keep going is part of surviving.",
    "SG089": "Earning money matters, but owning things that grow in value can help more.",
    "SG090": "Learn what only looks valuable and what truly creates value.",
    "SG091": "Learning about money can turn a paycheck into more choices.",
    "SG092": "If you spend every raise, it gets harder to save for more choices later.",
    "SG093": "Know where your money goes before you celebrate a purchase.",
    "SG094": "Build income that can keep helping you even when you are not working.",
    "SG095": "Money gets easier to manage when you learn how it works.",
    "SG096": "More income helps less if every raise is spent.",
    "SG097": "Good money choices depend on habits as much as intelligence.",
    "SG098": "Wealth often comes from money you choose not to spend.",
    "SG099": "Knowing what is enough can stop you from always wanting what others have.",
    "SG100": "Good long-term plans leave room for mistakes and bad luck.",
    "SG101": "Money grows slowly when you give it enough time.",
    "SG102": "Make a money plan that fits you, not someone else.",
    "SG103": "Steady and sensible can beat smart but careless.",
    "SG104": "Money freedom means having more control over your time.",
    "SG105": "Deep focus is powerful. Guard your mind from constant noise.",
    "SG106": "Save your best attention for work that truly matters.",
    "SG107": "Your best work needs enough quiet time to focus without switching tasks.",
    "SG108": "A full schedule can still miss the work that matters most.",
    "SG109": "Practice focus like a skill instead of waiting to feel perfectly ready.",
    "SG110": "Every break costs time before you can focus again.",
    "SG111": "Deep work can create more value than always replying quickly.",
    "SG112": "One focused hour can beat several broken hours.",
    "SG113": "Every yes uses some of your limited time.",
    "SG114": "Do fewer things with care instead of many things with anger.",
    "SG115": "If something is not important, say no and make room for what is.",
    "SG116": "Things get clearer when you separate what matters from what is only noise.",
    "SG117": "Protect the few things that matter most from the many things that do not.",
    "SG118": "Free time is not wasted time. It makes room for what matters.",
    "SG119": "Saying no can leave more time for what matters.",
    "SG120": "Simple choices matter more when they serve a clear goal.",
    "SG121": "Progress gets faster when your best attention goes to one important task first.",
    "SG122": "Ask which task would make the rest easier instead of treating every task the same.",
    "SG123": "Big results often come from choosing the right next thing again and again.",
    "SG124": "Doing many things at once can look busy without moving you forward.",
    "SG125": "Do the work that matters most before the noisy work takes over.",
    "SG126": "Your calendar should show what you say matters most.",
    "SG127": "Finish one big task before you start many new ones.",
    "SG128": "Your mind is better at making ideas than remembering every task.",
    "SG129": "Write down what you must do so your brain can stop holding it all.",
    "SG130": "When a task feels confusing, ask what you need to do next. Start there.",
    "SG131": "Plan work by what can actually be done, not by what sounds impressive.",
    "SG132": "Review your lists often so they stay useful instead of becoming clutter.",
    "SG133": "Clear next steps make big work feel lighter.",
    "SG134": "Choose the next small action before a big project starts feeling scary.",
    "SG135": "Steady effort over time can matter more than early talent.",
    "SG136": "Love for a goal gets stronger when you keep going through boring parts.",
    "SG137": "Practice gets better when you work on weak spots, not only strengths.",
    "SG138": "It is easier to keep going when your goal means more than looking impressive.",
    "SG139": "Talent may open the door, but steady effort takes you farther.",
    "SG140": "A hard season does not always mean you chose the wrong path.",
    "SG141": "Steady effort for years can beat a short burst of hard work.",
    "SG142": "Courage can look awkward. You still grow when you try anyway.",
    "SG143": "It can take courage to share how you feel.",
    "SG144": "Real connection grows when people meet the real you, not a performance.",
    "SG145": "Shame gets smaller when you talk honestly with someone safe.",
    "SG146": "Do not wait to feel fearless before doing something brave.",
    "SG147": "Being honest may feel risky, but it can create deeper connection.",
    "SG148": "Living fully means being willing to be imperfect in front of people.",
    "SG149": "Good leaders do not put off hard talks.",
    "SG150": "Clear rules are kind. They help people know what to do.",
    "SG151": "Trust grows through small actions done again and again.",
    "SG152": "A brave leader makes room for hard truths.",
    "SG153": "A leader can admit they are unsure and still take responsibility.",
    "SG154": "Good feedback can help people grow without making them feel small.",
    "SG155": "Strong teams grow where people practice courage, not just praise it.",
    "SG156": "Belonging should not require you to pretend to be someone else.",
    "SG157": "You are worthy while you are still learning and growing.",
    "SG158": "Build a life that feels true, not one that only looks impressive.",
    "SG159": "You do not need to attack yourself to grow. Kindness can help you change.",
    "SG160": "Rest, play, and creativity are part of life, not prizes for later.",
    "SG161": "Be yourself, even when some people do not approve.",
    "SG162": "Being imperfect is part of being human. It does not mean you failed.",
    "SG163": "Act before doubt turns a small choice into a long argument in your head.",
    "SG164": "Courage gets easier when you take the first step quickly.",
    "SG165": "Feelings matter, but they do not have to control every good choice.",
    "SG166": "Start before your mind has time to build a long excuse.",
    "SG167": "A tiny action can help you get started.",
    "SG168": "Confidence often grows after you act, not before.",
    "SG169": "Move when your gut says go, even if fear says wait.",
    "SG170": "Other people's choices feel lighter when you stop trying to control them.",
    "SG171": "Watch what people do. Their actions can answer many questions.",
    "SG172": "Freedom grows when you focus on what you can control.",
    "SG173": "People can misunderstand you. You can still keep going.",
    "SG174": "Stop forcing people to be close, agree, or approve of you.",
    "SG175": "Accepting what is real does not mean you like it. It helps you respond.",
    "SG176": "Stop trying to control others and focus on your own next step.",
    "SG177": "Some old habits once kept you safe but may not help you now.",
    "SG178": "Some bad habits once helped you feel safe. You can understand them and still change.",
    "SG179": "Growth may mean leaving pain that feels familiar for something new.",
    "SG180": "A strong reaction can be a clue. It does not have to control you.",
    "SG181": "Growing up means facing today, not living in the past.",
    "SG182": "An old survival habit may be blocking the life you want next.",
    "SG183": "Healing becomes real when what you learn starts changing what you do.",
    "SG184": "Life can feel different when you tell yourself the truth about it.",
    "SG185": "Feeling uneasy does not always mean something is wrong.",
    "SG186": "Do not measure progress only by what other people can see.",
    "SG187": "Old patterns are easier to change when you stop making excuses for them.",
    "SG188": "Answers get clearer when you stop forcing the one you wanted.",
    "SG189": "Notice how you react again and again. It may teach you something.",
    "SG190": "Seeing a problem in a new way can make it easier to solve.",
    "SG191": "Success can feel empty if your inner life gets ignored.",
    "SG192": "Protect your mind as carefully as you protect your work.",
    "SG193": "Daily effort can build a calm life without making your dreams smaller.",
    "SG194": "Your calendar shows what you truly make time for.",
    "SG195": "Simple daily habits can help you feel like yourself again.",
    "SG196": "Things can make life easier without giving life more meaning.",
    "SG197": "Build a life you enjoy living, not one you always want to escape.",
    "SG198": "Start your day on your terms before other people fill it.",
    "SG199": "Early hours can be useful because fewer people are asking for your time.",
    "SG200": "Move your body, think, and learn before the day gets busy.",
    "SG201": "A good morning cannot fix everything, but it can help you face the day better.",
    "SG202": "Waking early matters less than using that time well.",
    "SG203": "Use quiet time to build yourself, not only to watch more content.",
    "SG204": "Your morning routine should help your life, not prove you are better.",
    "SG205": "Your life changes when your choices get stronger than your excuses.",
    "SG206": "Ask more from yourself and keep getting better.",
    "SG207": "Ask questions that lead you toward useful action.",
    "SG208": "You can break a bad mood by changing what you focus on and do next.",
    "SG209": "Goals feel stronger when they connect to who you want to become.",
    "SG210": "Notice whether your habits are chasing comfort or building a better life.",
    "SG211": "You grow stronger when you stop treating old habits like they can never change.",
    "SG212": "Learn from people who do something well instead of thinking success is magic.",
    "SG213": "How you move, focus, and speak can change how well you perform.",
    "SG214": "Good talks depend on how the other person hears your words.",
    "SG215": "Old beliefs can limit you until new experience proves they can change.",
    "SG216": "Study what works, then test what fits your own life.",
    "SG217": "Try another way when the first way stops working.",
    "SG218": "Stand tall and move with confidence. Your mind may follow.",
    "SG219": "Do not let old habits decide what you think is possible.",
    "SG220": "Confidence grows when you act before you feel fully sure.",
    "SG221": "Excuses may feel safe, but they can cost you chances.",
    "SG222": "Treat people as important. It can make you a better leader.",
    "SG223": "Big goals need real steps, not just bigger dreams.",
    "SG224": "Action can make fear smaller when thinking makes it grow.",
    "SG225": "How you see yourself can limit you before life does.",
    "SG226": "Hope gives your effort somewhere to go when life feels heavy.",
    "SG227": "Hope can help you notice better choices.",
    "SG228": "Practice thoughts that help you act instead of thoughts that make you give up.",
    "SG229": "Confidence gets steadier when one result does not decide your worth.",
    "SG230": "Give worry less time in your mind, and peace gets more room.",
    "SG231": "Hope helps most when it keeps you working on real problems.",
    "SG232": "Practice thoughts that help you instead of repeating ones that hurt you.",
    "SG233": "What you tell yourself often can start to feel true.",
    "SG234": "Picture the result you want, then work toward it.",
    "SG235": "Question old beliefs because they can quietly shape what you do.",
    "SG236": "Go to sleep with one calm question instead of replaying the whole argument.",
    "SG237": "The way you talk to yourself can help you or hold you back.",
    "SG238": "Picture a good next step until taking action feels normal.",
    "SG239": "Do not let an old belief keep choosing for you today.",
    "SG240": "Repeated thoughts can slowly shape the kind of person you become.",
    "SG241": "Be careful what ideas you repeat because they can shape your actions.",
    "SG242": "Life can be hard, but your habits still shape how you respond.",
    "SG243": "A trained mind helps you make calmer choices.",
    "SG244": "Your thoughts can shape the choices you repeat.",
    "SG245": "Calm thoughts can be stronger than loud feelings.",
    "SG246": "What happens inside you often shows up in how you live.",
    "SG247": "Small choices become important when you repeat them over time.",
    "SG248": "What you do every day can shape your future before you see results.",
    "SG249": "Track what you do so you can learn why you get certain results.",
    "SG250": "It is easier to keep moving than to start again from zero.",
    "SG251": "Success can grow from small choices repeated for a long time.",
    "SG252": "Your habits can help your future or make it harder.",
    "SG253": "Do not underestimate what a year of small repeated choices can become.",
    "SG254": "The easy choice you skip today may matter after hundreds of repeats.",
    "SG255": "Simple habits grow powerful because time keeps adding to them.",
    "SG256": "Progress can be invisible before it becomes easy to see.",
    "SG257": "Small choices can build success or slowly move you the other way.",
    "SG258": "Do not judge a habit only by today's result.",
    "SG259": "Steady effort can turn small actions into big results.",
    "SG260": "Your path matters before the finish is clear.",
    "SG261": "Do the hardest useful task before easy work steals your time.",
    "SG262": "Your priorities are real only when your actions show them.",
    "SG263": "Plan tomorrow before today ends. It can make mornings easier.",
    "SG264": "Break big work into one small step you can start now.",
    "SG265": "Your busiest task is not always your most important one.",
    "SG266": "You get more done when you stop perfecting work that matters less.",
    "SG267": "Start with the task that will bring the most progress or relief.",
    "SG268": "Start the day by helping yourself grow before other demands take over.",
    "SG269": "A little quiet, movement, and planning can make mornings better.",
    "SG270": "Your morning can be short and still help you start the day well.",
    "SG271": "Wake up with a reason stronger than the snooze button.",
    "SG272": "A steady morning habit can help when the rest of life feels messy.",
    "SG273": "Use the first part of the day to get ready for what comes next.",
    "SG274": "A morning routine should help your life, not become another thing to show off.",
    "SG275": "Shorter plans can make faraway goals feel easier to act on.",
    "SG276": "Treat each week as important enough to plan and review.",
    "SG277": "Goals work better when you turn them into clear actions for this week.",
    "SG278": "Big yearly goals feel easier when you focus on the next twelve weeks.",
    "SG279": "Track the actions you can control, not only the final result.",
    "SG280": "Being responsible should help you change, not make you feel ashamed.",
    "SG281": "A close deadline can help you focus.",
    "SG282": "Make good money choices automatic so you do not rely on willpower every payday.",
    "SG283": "Spend freely on what truly matters to you and cut back on the rest.",
    "SG284": "A simple investing plan you start can beat perfect knowledge you never use.",
    "SG285": "Plan what you save, spend, borrow, and invest together.",
    "SG286": "Use money to support the life you want, not someone else's lifestyle.",
    "SG287": "Try to lower big costs because tiny savings cannot fix every large bill.",
    "SG288": "Keep good money habits even on days you do not feel like it.",
    "SG289": "Save for your future before you spend everything today.",
    "SG290": "Money you save and invest can grow into more money.",
    "SG291": "Do not put money into something you do not understand.",
    "SG292": "Learn how to earn more and save more of what you earn.",
    "SG293": "Ask advice from people who actually know the subject.",
    "SG294": "Wealth starts with good money habits before big money comes.",
    "SG295": "Spend less than you earn without giving up what matters to you.",
    "SG296": "Not every opinion about you deserves a place in your decisions.",
    "SG297": "Freedom can mean choosing what fits you, even if others disagree.",
    "SG298": "Know what is your job to handle and what belongs to someone else.",
    "SG299": "Your past affects you, but it does not control your next choice.",
    "SG300": "Things get worse when every talk feels like a contest.",
    "SG301": "Helping others can give life meaning even when nobody praises you.",
    "SG302": "Your past can explain you, but it does not decide how you live now.",
    "SG303": "You are the one noticing your thought. The thought is not all of you.",
    "SG304": "You do not have to obey every feeling right away.",
    "SG305": "Let hard things hurt, then let them go.",
    "SG306": "Notice the voice in your head, but do not believe everything it says.",
    "SG307": "Holding too tightly to comfort can make your life smaller.",
    "SG308": "Noticing a hard feeling can give you space before you react.",
    "SG309": "Letting go gets easier when you stop demanding that everything go your way.",
    "SG310": "Happiness can grow through small changes, not one huge change.",
    "SG311": "Know yourself well enough to choose habits that truly fit you.",
    "SG312": "Small joys deserve a place in a busy life.",
    "SG313": "People feel closer when you show thanks more often.",
    "SG314": "A little order and calm can change how a home feels.",
    "SG315": "Do not postpone happiness until every big goal is finished.",
    "SG316": "Try different ways to live instead of assuming one path fits everyone.",
    "SG317": "Let happiness help your work instead of waiting until work is over to feel good.",
    "SG318": "Train yourself to notice progress and chances, not only danger.",
    "SG319": "Small good habits can help you stay strong when pressure rises.",
    "SG320": "Close relationships can help success, not get in its way.",
    "SG321": "How you think about stress can change how you handle it.",
    "SG322": "Success lasts longer when your health helps support it.",
    "SG323": "Feeling good can help your mind see more possible solutions.",
    "SG324": "You do not need the whole plan. Try something small and learn from it.",
    "SG325": "There is more than one good path to a happy life.",
    "SG326": "You do not need a perfect plan. Try something and learn what comes next.",
    "SG327": "Notice what gives you energy and what keeps draining it.",
    "SG328": "If a problem cannot be solved, try looking at it in a new way.",
    "SG329": "Try small tests instead of thinking forever about a work choice.",
    "SG330": "Use what you learn to move forward, even when the old plan changes.",
    "SG331": "Creativity returns when you stop judging every new idea too soon.",
    "SG332": "Write before your inner critic talks you out of starting.",
    "SG333": "Protect time to make things that do not need to impress anyone.",
    "SG334": "You get more creative when you practice and let yourself play.",
    "SG335": "Notice what makes you curious and happy. It may lead you somewhere useful.",
    "SG336": "Your work can be imperfect and still matter.",
    "SG337": "Create often enough that you do not have to wait for inspiration.",
    "SG338": "Sleep is not wasted time. It prepares your body for tomorrow.",
    "SG339": "Treat bedtime like it matters. Protect your sleep.",
    "SG340": "Your work gets worse when you never make time to recover.",
    "SG341": "A rested brain learns more, feels calmer, and makes better choices.",
    "SG342": "Regular sleep matters as much as working hard during the day.",
    "SG343": "Do not keep losing sleep and expect your body to ignore it.",
    "SG344": "Recovery is part of getting things done, not the opposite.",
    "SG345": "A good life can grow from useful work, close people, movement, and small daily joys.",
    "SG346": "Purpose does not need to be huge. It can be a reason to get up tomorrow.",
    "SG347": "Stay connected to people who make life feel shared.",
    "SG348": "Keep doing work that uses your hands, mind, or heart.",
    "SG349": "Small joys can make life better when you notice them often.",
    "SG350": "Moving often during the day can matter more than rare bursts of hard exercise.",
    "SG351": "Life feels fuller when you help, enjoy, learn, and connect with people.",
    "SG352": "Remember what you have survived. It proves you can handle hard days.",
    "SG353": "Hard things can make you stronger when you choose them wisely.",
    "SG354": "Your past can explain you, but it does not excuse staying stuck.",
    "SG355": "Own your part when excuses start taking over.",
    "SG356": "Remember the hard things you have already done when you start doubting yourself.",
    "SG357": "Push a little past the first urge to quit, but respect real pain and injury.",
    "SG358": "Mental strength grows when you prove to yourself that you can do hard things.",
    "SG359": "Finish one small task. It can make the next task easier.",
    "SG360": "Small habits can steady you when the whole day feels messy.",
    "SG361": "Do not judge someone before you know what they have been through.",
    "SG362": "Strong people also know when to ask a team for help.",
    "SG363": "Failure can teach you when you return and try with more steady effort.",
    "SG364": "Hope can mean continuing the work before you see the result.",
    "SG365": "Improve what you can control, then move on to the next thing.",
}


_HARD_WORDS = re.compile(
    r"\b(?:"
    r"abundance|accountability|adaptability|authority|bureaucracy|"
    r"conditioning|conformity|consumption|conviction|diminishment|"
    r"expertise|financial independence|influence|institution|intentional|"
    r"negotiation|perfectionism|physiology|reciprocity|resentment|scarcity|"
    r"scrutiny|speculation|superiority|sustainable|vulnerable|"
    r"destabilize|passivity|authorship|obligation|capital"
    r")\b",
    re.IGNORECASE,
)


def apply_men_quote_clarity(row: dict[str, str]) -> dict[str, str]:
    """Apply Men-only simple-language copy without changing attribution metadata."""
    updated = dict(row)
    quote_id = (updated.get("QuoteID") or updated.get("ID") or "").strip()
    if quote_id in MEN_QUOTE_OVERRIDES:
        updated["Quote"] = MEN_QUOTE_OVERRIDES[quote_id]
    return updated


def is_clear_men_quote(row: dict[str, str]) -> bool:
    """Return True when Men production copy is short and easy to understand."""
    quote = (row.get("Quote") or "").strip()
    words = re.findall(r"[A-Za-z’'-]+", quote)
    if not words or len(words) > 18:
        return False

    letter_counts = [len(re.sub(r"[^A-Za-z]", "", word)) for word in words]
    average_word_length = sum(letter_counts) / len(letter_counts)
    if average_word_length > 5.2:
        return False

    if ";" in quote or ":" in quote:
        return False

    if _HARD_WORDS.search(quote):
        return False

    return True
