"""Women-only quote clarity rules for the live publishing pool.

The source libraries remain attribution-rich reference data. These overrides
simplify selected production copy so a reader around age 10 can understand the
message on the first read. Shared Self-Growth rows are not changed for Men.
"""

from __future__ import annotations

import re


WOMEN_QUOTE_OVERRIDES: dict[str, str] = {
    "SG006": "Improve the way you work instead of staring only at the result.",
    "SG015": "Rest before you are too tired to care about what matters.",
    "SG023": "Correct someone without making them feel small.",
    "SG031": "Belief helps, but action is what moves you forward.",
    "SG039": "Be present. See what is happening before you act.",
    "SG042": "People's reactions often say more about them than about your worth.",
    "SG045": "You feel freer when other people's opinions stop defining you.",
    "SG064": "Where you are today does not decide where you can go.",
    "SG083": "A solution that worked before may not work forever.",
    "SG084": "Move on before anger keeps you stuck in the old place.",
    "SG085": "Fear gets smaller when you explore instead of only imagining.",
    "SG094": "Build income that can keep helping you even when you are not working.",
    "SG102": "Make a money plan that fits you, not someone else.",
    "SG118": "Free time is not wasted time. It makes room for what matters.",
    "SG121": "Progress gets faster when your best attention goes to one important task first.",
    "SG125": "Do the work that matters most before the noisy work takes over.",
    "SG129": "Write down your commitments so your brain does not have to hold them all.",
    "SG139": "Talent opens the door, but steady effort takes you farther.",
    "SG155": "Strong teams grow where people practice courage, not just praise it.",
    "SG170": "Other people's choices feel lighter when you stop trying to control them.",
    "SG171": "Watch what people do. Their actions can answer many questions.",
    "SG173": "People can misunderstand you. You can still keep going.",
    "SG174": "Stop forcing people to be close, agree, or approve of you.",
    "SG179": "Growth may mean leaving pain that feels familiar for something new.",
    "SG180": "A strong reaction can be a clue. It does not have to control you.",
    "SG187": "Old patterns are easier to change when you stop making excuses for them.",
    "SG189": "Notice the reactions you keep repeating. They may teach you something.",
    "SG193": "Daily discipline can build a calm life without making your dreams smaller.",
    "SG204": "Your morning routine should help your life, not prove you are better.",
    "SG205": "Your life changes when your choices get stronger than your excuses.",
    "SG211": "You grow stronger when you stop treating old habits like they can never change.",
    "SG218": "Stand tall and move with confidence. Your mind may follow.",
    "SG220": "Confidence grows when you act before you feel fully sure.",
    "SG237": "The way you talk to yourself can help you or hold you back.",
    "SG242": "Life can be hard, but your habits still shape how you respond.",
    "SG261": "Do the hardest useful task before easy work steals your time.",
    "SG262": "Your priorities are real only when your actions show them.",
    "SG266": "You get more done when you stop perfecting work that matters less.",
    "SG267": "Start with the task that will bring the most progress or relief.",
    "SG279": "Track the actions you can control, not only the final result.",
    "SG288": "Keep good money habits even on days you do not feel like it.",
    "SG289": "Save for your future before you spend everything today.",
    "SG291": "Do not put money into something you do not understand.",
    "SG316": "Try different ways to live instead of assuming one path fits everyone.",
    "SG339": "Treat bedtime like it matters. Protect your sleep.",
    "SG363": "Failure can teach you when you return and try with more discipline.",
    "WEMP003": "One hard chapter does not define your whole story.",
    "WEMP014": "Your body deserves respect at every size and shape.",
    "WEMP018": "Your inner critic can be loud without being right.",
    "WEMP019": "Being kind at work does not mean making yourself easy to ignore.",
    "WEMP026": "Create before you know if anyone will praise it.",
    "WEMP027": "Do not talk yourself out of a chance before life answers.",
    "WEMP032": "You are worthy now. You do not have to become perfect first.",
    "WEMP034": "A boundary is not cruel just because someone wanted more access to you.",
    "WEMP040": "Notice the lessons life keeps trying to teach you.",
    "WEMP069": "Say what you mean. Do not hide your skill behind weak words.",
    "WEMP075": "Being seen gets easier each time you show up as yourself.",
    "WEMP077": "Do not let your own voice be the one that puts you down.",
    "WEMP079": "Not every misunderstanding needs a long fight to prove who you are.",
    "WEMP081": "Trust grows through actions you repeat, not words that sound good.",
    "WEMP084": "Say what you need before anger becomes the only way you speak.",
    "WEMP086": "Small caring habits can remind your body that you are safe.",
    "WEMP100": "You can care about equality and still admit when you get things wrong.",
    "WEMP102": "Trust yourself before you ask everyone else what they think.",
    "WEMP103": "Remember what you have learned and overcome. That can build confidence.",
    "WEMP123": "Build money safety before you try to look successful.",
    "WEMP134": "Set clear limits for your time, energy, body, money, and attention.",
    "WEMP136": "Take care of yourself like your health really matters.",
    "WEMP152": "You can let people down if pleasing them means hurting yourself.",
    "WEMP161": "Outgrowing your old self can feel strange before it feels freeing.",
    "WEMP164": "Caring for your health should never mean hating your body.",
    "WEMP204": "Strong women still need rest, support, routines, and good friends.",
    "WEMP207": "Women should not need extra courage just to speak in public.",
    "WEMP212": "You are allowed to name your pain, even when others want silence.",
    "WEMP216": "Speak before your answer feels perfect. It can still be useful.",
    "WEMP229": "Stop chasing equal effort from people who keep giving you less.",
    "WEMP233": "Listen to people who are different from you without losing your own values.",
    "WEMP234": "You do not need a long speech to explain a clear limit.",
    "WEMP238": "Make room for quiet before being busy becomes your whole life.",
    "WEMP243": "Being yourself can include truth, joy, new ideas, and freedom.",
    "WEMP246": "Build relationships where people share useful information and work toward the same goal.",
    "WEMP248": "Freedom is rarely given. People work together to create it.",
    "WEMP253": "Success matters, but liking the woman you become matters more.",
    "WEMP256": "Let her love science, sports, leadership, softness, strength, and whatever else fits her.",
    "WEMP268": "Your gifts cannot help anyone if you hide them forever.",
    "WEMP271": "Let your money choices match what matters to you.",
    "WEMP274": "Spend time with people who think women earning well is normal.",
    "WEMP275": "Success should give you more life, not take your life away.",
    "WEMP277": "Be more loyal to your goals than to your excuses.",
    "WEMP282": "Your worth is not measured by how much you get done.",
    "WEMP283": "Know who you are, even when someone disagrees with you.",
    "WEMP287": "Use your voice after wins and losses. Both can show leadership.",
    "WEMP289": "Hard times can change you without deciding your whole future.",
    "WEMP290": "Choose people who help you grow without making you defend yourself.",
    "WEMP291": "Changing direction does not mean your earlier path was wasted.",
    "WEMP297": "Good leaders care about people and still keep clear rules.",
    "WEMP298": "Stay curious. Listen before you decide you already know enough.",
    "WEMP304": "Your inner life needs care too, not just your public life.",
    "WEMP308": "Point out unfair rules before people start calling them normal.",
    "WEMP311": "Becoming someone new may mean leaving places where you had to stay quiet.",
    "WEMP314": "Your body can change and still deserve full respect.",
    "WEMP315": "You do not have to handle every hard thing perfectly to be worthy.",
    "WEMP321": "Shame makes money harder. Learning makes money easier to manage.",
    "WEMP326": "Your creativity can be joyful, bold, private, public, or just for you.",
    "WEMP327": "Make choices today that help your future self.",
    "WEMP330": "A woman can be strong and still be open with her feelings.",
    "WEMP334": "Clear limits can stop silent anger from hurting a relationship.",
    "WEMP340": "Success means less when you lose touch with yourself.",
    "WEMP342": "Love still needs honesty, respect, and clear limits.",
    "WEMP345": "Girls and boys both need education that teaches freedom and respect.",
    "WEMP352": "Being yourself may lose approval. Pretending costs more.",
    "WEMP303": "Your past can show your strength, but it does not limit your future.",
    "WEMP286": "Be kind to yourself now, not only after you get everything right.",
    "SG302": "Your past can explain you, but it does not decide how you live now.",
    "WEMP130": "Shame may make hiding feel safe, but you still deserve a full life.",
    "WEMP154": "You can feel confident without making anyone else feel small.",
    "WEMP312": "Healing is about getting better, not becoming easier for other people.",
    "SG352": "Remember what you have survived. It proves you can handle hard days.",
    "WEMP060": "You do not need the loudest voice to speak against something unfair.",
    "SG311": "Know yourself well enough to choose habits that truly fit you.",
    "SG117": "Protect the few things that matter most from the many things that do not.",
    "SG070": "Do not let comfort make every important choice for you.",
    "WEMP029": "Let people show you who they are. You do not have to change them.",
    "WEMP336": "Make your own life feel special, even when you are alone.",
    "SG299": "Your past affects you, but it does not control your next choice.",
    "WEMP051": "A woman can want big things without thinking she is better than others.",
    "WEMP337": "Your strength grows when you help other women grow too.",
    "SG230": "Give worry less time in your mind, and peace gets more room.",
    "SG071": "Say no to small fights so you have energy for what matters.",
    "WEMP120": "Build your own money options even while the system is unfair.",
    "SG305": "Let hard things hurt without carrying them forever.",
    "WEMP038": "Success costs too much when it hurts your body and mind.",
    "SG192": "Protect your mind as carefully as you protect your work.",
    "WEMP076": "Your ideas deserve time even before they make money.",
    "WEMP285": "Sometimes you are the problem, and sometimes you can fix it.",
    "WEMP240": "Your story can teach you without making you feel ashamed forever.",
    "SG231": "Hope helps most when it keeps you working on real problems.",
    "WEMP151": "Ask for the job, raise, support, and credit you need.",
    "WEMP354": "Stay close to people and habits that help you remember who you are.",
    "SG030": "Opportunities are easier to notice when you are already preparing.",
    "WEMP305": "Teach boys to respect all women, not only the women they love.",
    "SG178": "Some bad habits once helped you feel safe. You can understand them and still change.",
    "WEMP061": "You can love where you came from and still choose a different life.",
    "SG247": "Small choices become important when you repeat them over time.",
    "SG198": "Start your day on your terms before other people fill it.",
    "WEMP219": "Your work should not depend on always being the easiest person to please.",
    "WEMP052": "Do not build a life that looks good but feels wrong to live.",
    "WEMP225": "Your voice gets stronger when you use it before it sounds perfect.",
    "WEMP346": "You can lead differently and still be a strong leader.",
    "SG219": "Do not let old habits decide what you think is possible.",
    "SG286": "Use money to support the life you want, not someone else's lifestyle.",
    "WEMP012": "What happened to you is not the whole story of who you are.",
    "SG234": "Picture the result you want, then work toward it.",
    "SG336": "Your work can be imperfect and still matter.",
    "WEMP361": "You can build a new life without pretending your past never happened.",
    "WEMP267": "Give your team credit without hiding your own work.",
    "WEMP071": "Teach women how to build wealth, not just feel guilty about spending.",
    "WEMP353": "Keep growing even after success, praise, or a big milestone.",
    "WEMP288": "Success should leave you enough energy to enjoy your life.",
    "SG046": "Speak clearly so people do not have to guess what you mean.",
    "WEMP228": "Be brave before your excuses have time to grow.",
    "WEMP365": "You are enough before the next big win.",
    "SG186": "Do not measure progress only by what other people can see.",
    "WEMP011": "Learning can help a woman question things she was told to accept.",
    "SG252": "Your habits can help your future or make it harder.",
    "WEMP017": "A strength can become a problem if you use it in every situation.",
    "WEMP091": "You do not need to see the whole path to take the next step.",
    "SG029": "A goal needs a plan, and plans can change when you learn more.",
    "SG151": "Trust grows through small actions repeated over time.",
    "SG054": "Pain is hard, but you can still face it with self-respect.",
    "WEMP360": "Every girl deserves the chance to imagine a bigger future.",
    "SG270": "Your morning can be short and still help you start the day well.",
    "WEMP119": "Do not keep doing unseen office tasks while others get credit for leading.",
    "WEMP074": "Ask what your work is worth before worrying that you are asking too much.",
    "WEMP015": "You do not have to keep proving that you deserve to be in the room.",
    "WEMP364": "You deserve to take up space without feeling sorry for it.",
    "SG050": "Having a reason to keep going can help you carry hard times.",
    "WEMP210": "One girl speaking up can reveal unfairness that others were told to accept.",
    "WEMP172": "Charging too little is not humble if your work cannot survive.",
    "WEMP276": "Start before it is perfect. Making something teaches you how to improve it.",
    "SG236": "Go to sleep with one calm question instead of replaying the whole argument.",
    "SG138": "It is easier to keep going when your goal means more than looking impressive.",
    "SG009": "Your power often begins with choosing how you respond.",
    "SG092": "If you spend every raise, it gets harder to save for more choices later.",
    "WEMP036": "Do not wait for someone else to give you the care you need.",
    "SG165": "Feelings matter, but they do not have to control every good choice.",
    "SG224": "Taking action can shrink fears that thinking keeps growing.",
    "SG052": "Ask what you can learn from this hard season, not only when it will end.",
    "SG268": "Start the day by helping yourself grow before other demands take over.",
    "SG113": "Every yes uses some of your limited time.",
    "SG095": "Money gets easier to manage when you learn how it works.",
    "SG033": "A lot of worry comes from a future that has not happened yet.",
    "SG342": "Regular sleep matters as much as working hard during the day.",
    "WEMP218": "Choose what matters to you over being liked by everyone.",
    "SG169": "Move when your gut says go, even if fear says wait.",
    "SG062": "Work smarter by noticing what is and is not working.",
    "SG140": "A hard season does not always mean you chose the wrong path.",
    "SG314": "A little order and calm can change how a home feels.",
    "SG098": "Wealth often comes from money you choose not to spend.",
    "SG343": "Do not keep losing sleep and expect your body to ignore it.",
    "WEMP280": "Name the fear so it does not quietly control the room.",
    "WEMP039": "You can build a good life even when your old plan is gone.",
    "SG250": "It is easier to keep moving than to start again from zero.",
    "WEMP241": "Do not let someone else's rush decide what matters to you.",
    "SG055": "A reason to keep going can help when life cannot change right away.",
    "SG203": "Use quiet time to build yourself, not only to watch more content.",
    "SG195": "Simple daily habits can help you feel like yourself again.",
    "SG295": "Spend less than you earn without giving up what matters to you.",
    "SG312": "Small joys deserve a place in a busy life.",
    "WEMP073": "Debt is a problem to solve, not a reason to judge yourself.",
    "SG323": "Feeling good can help your mind see more possible solutions.",
    "WEMP068": "Do not wait for fear to leave before doing work that matters to you.",
    "SG209": "Goals feel stronger when they connect to who you want to become.",
    "SG249": "Track what you do so you can learn why you get certain results.",
    "SG293": "Ask advice from people who actually know the subject.",
    "WEMP252": "Your life becomes yours when you stop thinking you must always obey to be good.",
    "WEMP041": "You learn what matters by noticing what makes you feel useful and alive.",
    "SG146": "Do not wait to feel fearless before doing something brave.",
    "SG361": "Do not judge someone before you know what they have been through.",
    "SG097": "Good money choices depend on habits as much as intelligence.",
    "SG176": "Stop trying to control others and focus on your own next step.",
    "WEMP191": "You find direction by trying things and noticing what keeps drawing you back.",
    "WEMP080": "Being open about your feelings is not weak. It can bring people closer.",
    "SG119": "Saying no can leave more time for what matters.",
    "SG099": "Knowing what is enough can stop you from always wanting what others have.",
    "WEMP293": "Spend time alone sometimes so you can hear your own thoughts clearly.",
    "SG184": "Life can feel different when you tell yourself the truth about it.",
    "SG131": "Plan work by what can actually be done, not by what sounds impressive.",
    "SG290": "Money you save and invest can grow into more money.",
    "SG162": "Being imperfect is part of being human. It does not mean you failed.",
    "SG206": "Ask more from yourself and keep getting better.",
    "SG365": "Improve what you can control, then move on to the next thing.",
    "SG132": "Review your lists often so they stay useful instead of becoming clutter.",
    "WEMP072": "Do not make your money goals smaller just to sound more acceptable.",
    "WEMP093": "A woman can lose trust in her instincts if people keep telling her she is wrong.",
    "SG283": "Spend freely on what truly matters to you and cut back on the rest.",
    "WEMP284": "Your yes means more when you know you are allowed to say no.",
    "WEMP320": "Do not let work rules decide how big a woman's goals can be.",
    "SG036": "Peace grows when you accept what is happening right now.",
    "SG082": "Notice small changes early so you do not have to react in panic.",
    "SG007": "Make good habits easier and bad habits harder.",
    "WEMP094": "Talent needs space to grow. Every woman deserves some space of her own.",
    "SG037": "Life is happening now, even when your mind keeps wandering away.",
    "WEMP099": "A design can fail women when it assumes men are the default.",
    "SG257": "Small choices can build success or slowly move you the other way.",
    "SG276": "Treat each week as important enough to plan and review.",
    "WEMP355": "Feminism is strongest when freedom is treated as a basic human right.",
    "SG281": "A close deadline can help you focus.",
    "WEMP049": "When women are missing from the data, unfair decisions can look normal.",
    "SG322": "Success lasts longer when health supports it.",
    "SG086": "Being able to adapt can matter more than proving you were right.",
    "SG201": "A good morning cannot fix everything, but it can help you face the day better.",
    "WEMP343": "Women need stories that remind them their lives belong to them.",
    "SG190": "Seeing a problem in a new way can make it easier to solve.",
    "SG278": "Big yearly goals feel easier when you focus on the next twelve weeks.",
    "SG160": "Rest, play, and creativity are part of life, not prizes you earn later.",
    "WEMP306": "Teach her that marriage is a choice, not a measure of her success.",
    "WEMP053": "Be proud of where you come from without letting it limit where you go.",
    "SG061": "One bad result does not define who you are.",
    "SG354": "Your past can explain you, but it does not excuse staying stuck.",
    "SG197": "Build a life you enjoy living, not one you always want to get away from.",
    "WEMP114": "Your body deserves respect even when other people do not approve.",
    "WEMP189": "Feeling joy again does not mean you have forgotten what you lost.",
    "WEMP185": "A strong reaction can teach you something without controlling what you do.",
    "WEMP101": "Speak up when your ideas matter. They deserve to be heard.",
    "WEMP175": "Courage can start with saying yes to one chance you would usually avoid.",
    "WEMP146": "You can lead in your own way. You do not have to copy old rules.",
    "WEMP142": "Self-love means not speaking to yourself in ways that hurt you.",
    "SG348": "Keep doing work that uses your hands, mind, or heart.",
    "SG077": "Hope becomes stronger when it changes what you do.",
    "WEMP173": "Make good money habits easy to repeat, even on busy days.",
    "SG021": "A thank-you means more when you say exactly what you are thankful for.",
    "SG013": "Listen to understand someone, not just to plan your reply.",
    "SG041": "Use words that do less harm.",
    "SG152": "A brave leader makes room for hard truths.",
    "SG248": "What you do every day can shape your future before you see results.",
    "SG200": "Move your body, think, and learn before the day gets busy.",
    "WEMP078": "Confidence often comes after you act, not before.",
    "SG035": "You can notice a thought without letting it decide who you are.",
    "SG239": "Do not let an old belief keep choosing for you today.",
    "SG172": "Freedom grows when you focus on what you can control.",
    "SG104": "Money freedom means having more control over your time.",
    "SG188": "Answers get clearer when you stop forcing the one you wanted.",
    "WEMP133": "What you believe matters most when it is hard to stand by it.",
    "SG349": "Small joys can make life better when you notice them often.",
    "SG167": "A tiny action can help you get started.",
    "WEMP148": "Women's stories can give other women courage and new ideas.",
    "SG292": "Learn how to earn more and save more of what you earn.",
    "WEMP244": "Make time for your own ideas before other people's needs take the whole day.",
    "SG345": "A good life can grow from useful work, close people, movement, and small daily joys.",
    "SG359": "Finish one small task. It can make the next task easier.",
    "SG306": "Notice the voice in your head, but do not believe everything it says.",
    "SG115": "If something is not important, say no and make room for what is.",
    "SG273": "Use the first part of the day to get ready for what comes next.",
    "WEMP199": "Before trusting a solution for everyone, ask who was included when it was made.",
    "SG130": "A confusing task feels harder. Decide the next clear step.",
    "WEMP108": "Judge women leaders by their choices, not by whether everyone likes them.",
    "WEMP356": "Show girls many examples of women living good lives in different ways.",
    "SG040": "Do not let yesterday and tomorrow steal all of today.",
    "SG264": "Break big work into one small step you can start now.",
    "WEMP113": "Equality is not real if some women are ignored because of race or background.",
    "SG088": "When life changes, learning how to keep going is part of surviving.",
    "SG122": "Ask which task would make the rest easier instead of treating every task the same.",
    "WEMP318": "Fear often grows around the work that matters most to you.",
    "SG164": "Courage gets easier when you take the first step quickly.",
    "SG128": "Your mind is better at making ideas than remembering every task.",
    "WEMP125": "Do not build success that leaves you no time to enjoy your life.",
    "SG271": "Wake up with a reason stronger than the snooze button.",
    "WEMP141": "Notice the work that feels important even when no one praises it.",
    "WEMP328": "Women can feel afraid and still speak, apply, leave, ask, or begin.",
    "SG034": "Come back to this moment before your mind turns one problem into ten.",
    "WEMP158": "Other people's unfair opinions do not decide how good you are at something.",
    "WEMP131": "A strong leader can admit they do not know yet and still take charge.",
    "WEMP150": "You can enjoy a culture and still question what feels unfair.",
    "SG356": "Remember the hard things you have already done when you start doubting yourself.",
    "WEMP177": "Wanting more for your life does not mean you are not thankful for what you have.",
    "WEMP174": "Wanting to earn more does not mean you are not thankful.",
    "WEMP162": "Someone who was hurt should not have to be perfect before others believe them.",
}


_HARD_WORDS = re.compile(
    r"\b(?:"
    r"abandon|authority|conditioning|conformity|conviction|diminishment|"
    r"disposable|economic|expertise|financial independence|influence|"
    r"institution|intentional|negotiation|perfectionism|political awareness|"
    r"professional commitment|psychologically|reciprocity|resentment|scarcity|"
    r"scrutiny|solidarity|superiority|sustainable|visibility|vulnerable|"
    r"destabilize|material conditions|physiology|passivity|speculation|"
    r"authorship|obligation|capital"
    r")\b",
    re.IGNORECASE,
)


def apply_women_quote_clarity(row: dict[str, str]) -> dict[str, str]:
    """Apply a Women-only simple-language override without changing metadata."""
    updated = dict(row)
    quote_id = (updated.get("QuoteID") or updated.get("ID") or "").strip()
    if quote_id in WOMEN_QUOTE_OVERRIDES:
        updated["Quote"] = WOMEN_QUOTE_OVERRIDES[quote_id]
    return updated


def is_clear_women_quote(row: dict[str, str]) -> bool:
    """Return True when production copy is short and easy to understand."""
    quote = (row.get("Quote") or "").strip()
    words = re.findall(r"[A-Za-z’'-]+", quote)
    if not words or len(words) > 16:
        return False

    letter_counts = [len(re.sub(r"[^A-Za-z]", "", word)) for word in words]
    average_word_length = sum(letter_counts) / len(letter_counts)
    if average_word_length > 5.2:
        return False

    if ";" in quote or ":" in quote:
        return False

    if _HARD_WORDS.search(quote):
        return False

    return True
